version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sistempos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - DB_URL=postgres://user:password@db:5432/sistempos
    depends_on:
      - db

  frontend:
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db-data:
    driver: local
